### ISSUE TITLE
SELECT ... IN bind variables

### ISSUE THREAD

**Issue by milaniliev** [kubo/ruby-oci8#115] opened 2016-02-02 21:37 UTC
@kubo , thanks for writing oci-8 and helping us noobs :)

For the life of me, I cannot figure out how to do the following relatively simple statement:

```ruby
cursor = OCI8.parse("SELECT * FROM USERS WHERE ID IN :ids")
cursor.bind_param(":ids", [1,2,3])
cursor.exec()
```

This throws `Type Array not supported` error.

Seems like this should be simple. Am I missing something?

Best,
Milan

**Comment by yahonda** [comment] 2016-02-02 22:01
It looks like `bind_param_array` is the method for your needs.
http://www.rubydoc.info/gems/ruby-oci8/OCI8/Cursor#bind_param_array-instance_method

**Comment by milaniliev** [comment] 2016-02-02 22:05
@yahonda I used `bind_param_array`, but it has an odd limitation: all bound arrays MUST be the same length. So, in my case, if I had `id IN :ids AND name in :names`, the `ids` and `names` arrays MUST contain the same number of elements. This is, of course, impractical for real queries.

It looks like it's intended to be used to re-run statements multiple times - all the examples I've seen talk about reducing round-trips and improving query performance.

Unless I'm misunderstanding how the method should be used?

Thanks for your time in either case!

**Comment by yahonda** [comment] 2016-02-03 02:50
@milaniliev Thanks for the reply. Looks like `bind_param_array` was intended for DML statements and each bind size need to be equal based on the ChangeLog of this commit.
https://github.com/kubo/ruby-oci8/commit/a304c55d32dedece9178898733b5c30393ef9daf

**Comment by kubo** [comment] 2016-02-03 04:03
@milaniliev 

[IN condition](https://docs.oracle.com/database/121/SQLRF/conditions014.htm#SQLRF52169) doesn't accept an array.  It must be a subquery or an expression list.
You need to create an expression list whose length is same with the input data.
```
ids = [1,2,3]
place_holder_string = Array.new(ids.length) {|index| ":id#{index}"}.join(', ')
cursor = conn.parse("SELECT * FROM USERS WHERE ID IN (#{place_holder_string})")
ids.each_with_index do |id, index|
    cursor.bind_param("id#{index}", id) # bind each element
end
cursor.exec()
```

@yahonda 
`bind_param_array` is for `array DML` or `bulk DML`, which reduces the number of network round trips and improve performance of data loading (inserting).

The following code needs four network round trips.
```
ids = [1, 2, 3, 4]
names = ['scott', 'tiger', 'john', 'smith']
cursor = conn.parse('insert into users (:id, :name)')
1.upto(ids.length) do |index|
   cursor.bind_param(:id, ids[index])
   cursor.bind_param(:name, names[index])
   cursor.exec # one network round trip for each element
end
```
The number of network round trips is reduced by `bind_param_array`.
The following code needs only one network round trip.
```
ids = [1, 2, 3, 4]
names = ['scott', 'tiger', 'john', 'smith']
cursor = conn.parse_array('insert into users (:id, :name)')
cursor.max_array_size = ids.length
cursor.bind_param_array(:id, ids)
cursor.bind_param_array(:name, names)
cursor.exec_array # one network round trip
```

**Comment by milaniliev** [comment] 2016-02-03 04:18
@kubo do people tell you you're awesome often? Thank you! That would have
taken a while to figure out.

I see what the code is doing, and I think I get why. The difference between
"an array" and "an expression list" is not obvious at first, but I think I
get the gist.

Between this work and the bind_param sequence, simple use cases become a
little cumbersome. I'm thinking of making a tiny wrapper over ruby-oci8 to
enable executing queries with simple parameters, including this logic, and
the option of returning Hash arrays - while still giving full access to the
OCI8::Cursor and other underlying objects.

Something like:
```
cursor = database.execute("SELECT * FROM USERS WHERE ID IN :ids", {ids: [1,
2, 3]})
cursor.to_a # => [{name: "Bob", age: 40}, {....}]
```
Any objections/suggestions?

**Comment by kubo** [comment] 2016-02-14 13:33
I close this issue because the original issue itself was solved.

I'll add the following two methods in the next ruby-oci8 release
```ruby
class OCI8
  # Converts `array` to IN-condition bind names
  def self.in_cond_names(array)
    objid = format("%x", array.__id__) # this line may be changed.
    len = array.length
    len = 1 if len == 0 #  at least one element
    Array.new(len) do |index|
      ":in_cond_#{objid}_#{index}"
    end.join(', ')
  end

  # Converts `array` to IN-condition bind values
  def self.in_cond_values(array, type = nil, length = nil)
    array = [nil] if array.empty? # at least one element
    array.collect do |elem|
      if elem.nil? and type.nil?
        first_non_nil_elem = array.find do |e|
          e
        end
        [nil, first_non_nil_elem ? first_non_nil_elem.class : String]
      else
        [elem, type, length]
      end
    end
  end
end
```
and add the following sample.
```ruby
ids = [1,2,3]
cursor = conn.exec("SELECT * FROM USERS WHERE ID IN (#{OCI8.in_cond_names(ids)})", 
                   *OCI8.in_cond_values(ids))
while row = cursor.fetch
  p row
end
```

This uses the following undocumented usage of [OCI8#exec](http://www.rubydoc.info/github/kubo/ruby-oci8/OCI8#exec-instance_method). (I must fix the document.)
```ruby
cursor = conn.exec(sql_stmt,
                   [val_1, type_1, len_1],
                   [val_2, type_2, len_2],
                   [val_3, type_3, len_3])
```
is shorthand of the following code.
```ruby
cursor = conn.prepare(sql_stmt)
cursor.bind_param(1, val_1, type_1, len_1)
cursor.bind_param(2, val_2, type_2, len_2)
cursor.bind_param(3, val_3, type_3, len_3)
cursor.exec
```

**Closed by kubo** 2016-02-14 13:33 UTC

**Comment by milaniliev** [comment] 2016-02-14 14:06
Kubo,

Perfect, thank you!

Best,
Milan
