### ISSUE TITLE
Installation failure -- OS X Sierra 

### ISSUE THREAD

**Issue by bdh-umn** [kubo/ruby-oci8#141] opened 2016-10-03 21:09 UTC
I'm trying to install ruby-oci8 on OS X Sierra. Ruby 1.9.3-p551 via RVM, and Oracle instantclient 12.1. It's failing with a compilation error. Developer tools are installed and cc is functioning. I've attached the console output, the mkmf.log, and the relevant commands and outputs from your installation issue reporting page. Thanks. 

-Brian Hayden

[commands.txt](https://github.com/kubo/ruby-oci8/files/507202/commands.txt)
[console.txt](https://github.com/kubo/ruby-oci8/files/507201/console.txt)
[mkmf.txt](https://github.com/kubo/ruby-oci8/files/507204/mkmf.txt)
[output.txt](https://github.com/kubo/ruby-oci8/files/507200/output.txt)

**Comment by kubo** [comment] 2016-10-04 12:28
In console.txt:
```
checking for cc... *** extconf.rb failed ***
```
C compiler doesn't work.

In commands.txt and output.txt:
```shell
$ ruby -r rbconfig -e "p RbConfig::CONFIG['CC']"
"/usr/local/bin/gcc-4.9"
```
I guess that there is no `/usr/local/bin/gcc-4.9`.

If you have another compiler, fix `CONFIG["CC"]` in `/Users/bhayden/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/x86_64-darwin15.6.0/rbconfig.rb`.

**Comment by joshuaswilcox** [comment] 2016-10-20 15:00
@kubo I can confirm that changing that to `CONFIG["CC"] = '/usr/bin/gcc'` worked for me

**Comment by pipalbohar** [comment] 2016-11-21 09:14
@kubo 
Im trying to install on macOS Sierra 10.12.1, 
using ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16] and oracle instantclient 12.1. It is giving error
Error Message:
  Set the environment variable DYLD_LIBRARY_PATH, DYLD_FALLBACK_LIBRARY_PATH or
  OCI_DIR to point to the Instant client directory.
Attaching output on console and of commands
[commands-output.txt](https://github.com/kubo/ruby-oci8/files/603118/commands-output.txt)
[console-output.txt](https://github.com/kubo/ruby-oci8/files/603119/console-output.txt)

Can you please help

**Comment by kubo** [comment] 2016-11-21 22:46
@bdh-umn 
I close this issue. If my response has not solved it, add a new comment to this page.

@ebcaeddb 
You should have make a new issue because yours is unrelated to this except the platform.
```
  checking OCI_DIR...
  checking the default value of DYLD_FALLBACK_LIBRARY_PATH...
    checking /Users/pipal/lib... no
    checking /usr/local/lib... no
    checking /lib... no
    checking /usr/lib... no
```
No OCI_DIR was set.
If it is set, the output should be:
```
  checking OCI_DIR...
    checking /path/in/oci_dir... 
```
If you are sure that OCI_DIR is set, it may be unset by `sudo`.
Could you try `sudo env OCI_DIR=$OCI_DIR gem install ruby-oci8`?
If it doesn't fix your issue, make a new issue.

**Closed by kubo** 2016-11-21 22:46 UTC
